/**
 * Zorah Training — data model, API client and progress helpers.
 *
 * Content (curriculum, lessons, tasks, quizzes) is generated by the
 * backend's /training/* endpoints (Go and Pro only). A course and the
 * learner's progress are stored as one row in `training_courses`, with
 * every generated lesson / task / quiz cached in `progress` so a course
 * resumes exactly where it was left and nothing is generated twice.
 */
import { supabase } from "./supabase";
import type { Database, Json } from "./database.types";

const BASE = (import.meta.env.VITE_AI_BACKEND_URL as string | undefined)?.replace(/\/$/, "") ?? "";

export type Stage = "basic" | "intermediate" | "advanced" | "pro";
export const STAGES: Stage[] = ["basic", "intermediate", "advanced", "pro"];
export const STAGE_LABEL: Record<Stage, string> = {
  basic: "Basic",
  intermediate: "Intermediate",
  advanced: "Advanced",
  pro: "Pro",
};

// ---- content shapes (mirror backend/training/engine.py normalizers) -------
export interface LessonRef { id: string; title: string; summary: string }
export interface Module { title: string; lessons: LessonRef[] }
export interface Curriculum {
  title: string;
  overview: string;
  modules: Module[];
  roadmap?: { stage: Stage; focus: string }[];
}
export interface ChoiceQ {
  id: string; type: "choice"; prompt: string; options: string[];
  correct_index: number; explanation: string; hint: string;
}
export interface ShortQ { id: string; type: "short"; prompt: string; reference: string; hint: string }
export type LessonQ = ChoiceQ | ShortQ;
export interface LessonContent {
  title: string;
  objectives: string[];
  explanation_md: string;
  examples: { title: string; body_md: string }[];
  diagram_svg: string | null;
  diagram_caption: string;
  questions: LessonQ[];
}
export interface TaskTest { name: string; type: "call" | "stdout" | "behavior"; expr?: string; expected: string }
export interface TaskContent {
  title: string;
  instructions_md: string;
  kind: "code" | "written";
  language: string | null;
  execution: "javascript" | "python" | "none";
  starter_code: string;
  tests: TaskTest[];
  rubric: string[];
  hints: string[];
  solution: string | null;
}
export interface QuizQ {
  id: string; prompt: string; options: string[]; correct_index: number;
  explanation: string; why_wrong: (string | null)[];
}
export interface TaskReview { passed: boolean; score: number; feedback_md: string; next_steps: string[] }
export interface AnswerResult {
  correct: boolean;
  feedback_md: string;
  follow_up: { prompt: string; hint: string; reference: string } | null;
}

// ---- progress shapes -------------------------------------------------------
export interface QuestionRecord {
  answer: string;
  correct: boolean;
  feedback_md?: string;
  follow_up?: { prompt: string; hint: string; reference: string; answer?: string; feedback_md?: string };
}
export type Step = "learn" | "task" | "quiz" | "done";
export interface LessonState {
  step: Step;
  content?: LessonContent;
  answers: Record<string, QuestionRecord>;
  task?: TaskContent;
  taskCode?: string;
  taskAttempts: number;
  taskReview?: TaskReview;
  taskSkipped?: boolean;
  quiz?: { questions: QuizQ[] };
  quizAnswers: Record<string, number>;
  completedAt?: string;
}
export interface StageRecord { stage: Stage; completedAt: string; quizPct: number }
export interface Progress { lessons: Record<string, LessonState>; history: StageRecord[] }

export interface Course {
  id: string;
  subject: string;
  is_coding: boolean;
  language: string | null;
  level: string | null;
  stage: Stage;
  title: string;
  curriculum: Curriculum;
  progress: Progress;
  current_lesson_id: string | null;
  updated_at: string;
}

export const emptyLesson = (): LessonState => ({ step: "learn", answers: {}, taskAttempts: 0, quizAnswers: {} });
export const emptyProgress = (): Progress => ({ lessons: {}, history: [] });

// ---- API ----------------------------------------------------------------
async function authHeader(): Promise<Record<string, string>> {
  const { data } = await supabase.auth.getSession();
  const token = data.session?.access_token;
  return token ? { Authorization: `Bearer ${token}` } : {};
}

export class TrainingApiError extends Error {
  constructor(message: string, public status = 0) {
    super(message);
  }
}

async function post<T>(path: string, body: unknown): Promise<T> {
  if (!BASE) throw new TrainingApiError("The AI backend isn't configured.");
  const ctrl = new AbortController();
  // Generous: the free-tier backend can take ~50s to wake, then the model has to write.
  const timer = setTimeout(() => ctrl.abort(), 120000);
  try {
    const resp = await fetch(`${BASE}${path}`, {
      method: "POST",
      headers: { "Content-Type": "application/json", ...(await authHeader()) },
      body: JSON.stringify(body),
      signal: ctrl.signal,
    });
    if (!resp.ok) {
      const data = await resp.json().catch(() => null);
      const detail = typeof data?.detail === "string" ? data.detail : null;
      throw new TrainingApiError(
        detail ??
          (resp.status === 403
            ? "Training is available on the Go and Pro plans."
            : "The tutor hit a problem. Please try again."),
        resp.status,
      );
    }
    return (await resp.json()) as T;
  } catch (e) {
    if (e instanceof TrainingApiError) throw e;
    if (e instanceof DOMException && e.name === "AbortError")
      throw new TrainingApiError("That took too long — the server may be waking up. Try again in a moment.");
    throw new TrainingApiError("Couldn't reach the server. Check your connection and try again.");
  } finally {
    clearTimeout(timer);
  }
}

export interface CourseCtx {
  subject: string;
  is_coding: boolean;
  language: string | null;
  level: string | null;
  stage: Stage;
  course_title: string;
}
export const ctxOf = (c: Course): CourseCtx => ({
  subject: c.subject, is_coding: c.is_coding, language: c.language, level: c.level, stage: c.stage, course_title: c.title,
});

export const api = {
  curriculum: (p: { subject: string; is_coding: boolean; language: string | null; level: string | null; stage: Stage; focus?: string }) =>
    post<Curriculum>("/training/curriculum", p),
  lesson: (c: Course, lesson: LessonRef) =>
    post<LessonContent>("/training/lesson", {
      ...ctxOf(c), lesson, outline: c.curriculum.modules.flatMap((m) => m.lessons.map((l) => l.title)),
      mastery: masterySummary(c),
    }),
  answer: (p: { subject: string; lesson_title: string; question: string; user_answer: string; reference: string; options?: string[]; was_correct?: boolean }) =>
    post<AnswerResult>("/training/answer", p),
  task: (c: Course, lesson: LessonRef, performance: Record<string, unknown>) =>
    post<TaskContent>("/training/task", { ...ctxOf(c), lesson, performance }),
  reviewTask: (p: { subject: string; language: string | null; task: TaskContent; submission: string; mode: "review" | "tests"; run_result?: unknown; all_tests_passed?: boolean }) =>
    post<TaskReview>("/training/task/review", p),
  quiz: (c: Course, lesson: LessonRef, performance: Record<string, unknown>) =>
    post<{ questions: QuizQ[] }>("/training/quiz", { ...ctxOf(c), lesson, performance }),
};

// ---- persistence -----------------------------------------------------------
const COLS = "id,subject,is_coding,language,level,stage,title,curriculum,progress,current_lesson_id,updated_at";

function toCourse(row: Record<string, unknown>): Course {
  const progress = (row.progress as Progress | null) ?? emptyProgress();
  return {
    ...(row as unknown as Course),
    curriculum: row.curriculum as Curriculum,
    progress: { lessons: progress.lessons ?? {}, history: progress.history ?? [] },
  };
}

export async function listCourses(): Promise<Course[]> {
  const { data, error } = await supabase.from("training_courses").select(COLS).order("updated_at", { ascending: false });
  if (error) throw new Error(error.message);
  return (data ?? []).map((r) => toCourse(r as Record<string, unknown>));
}

export async function getCourse(id: string): Promise<Course | null> {
  const { data, error } = await supabase.from("training_courses").select(COLS).eq("id", id).maybeSingle();
  if (error) throw new Error(error.message);
  return data ? toCourse(data as Record<string, unknown>) : null;
}

export async function createCourse(p: {
  subject: string; is_coding: boolean; language: string | null; level: string | null; stage: Stage; curriculum: Curriculum;
}): Promise<Course> {
  const { data, error } = await supabase
    .from("training_courses")
    .insert({
      subject: p.subject, is_coding: p.is_coding, language: p.language, level: p.level, stage: p.stage,
      title: p.curriculum.title, curriculum: p.curriculum as unknown as Json, progress: emptyProgress() as unknown as Json,
      current_lesson_id: p.curriculum.modules[0]?.lessons[0]?.id ?? null,
    })
    .select(COLS)
    .single();
  if (error) {
    throw new Error(
      /row-level security|policy/i.test(error.message) ? "Training is available on the Go and Pro plans." : error.message,
    );
  }
  return toCourse(data as Record<string, unknown>);
}

export async function saveCourse(
  id: string,
  patch: Partial<Pick<Course, "progress" | "current_lesson_id" | "stage" | "curriculum" | "title">>,
) {
  const { error } = await supabase
    .from("training_courses")
    .update(patch as unknown as Database["public"]["Tables"]["training_courses"]["Update"])
    .eq("id", id);
  if (error) throw new Error(error.message);
}

export async function deleteCourse(id: string) {
  const { error } = await supabase.from("training_courses").delete().eq("id", id);
  if (error) throw new Error(error.message);
}

// ---- progress helpers -------------------------------------------------------
export const allLessons = (c: Course): LessonRef[] => c.curriculum.modules.flatMap((m) => m.lessons);
export const isDone = (c: Course, id: string) => c.progress.lessons[id]?.step === "done";

export function quizResult(s: LessonState | undefined): { correct: number; total: number } | null {
  const qs = s?.quiz?.questions;
  if (!qs?.length) return null;
  const answered = qs.filter((q) => s!.quizAnswers[q.id] !== undefined);
  if (answered.length < qs.length) return null;
  return { correct: qs.filter((q) => s!.quizAnswers[q.id] === q.correct_index).length, total: qs.length };
}

export function courseStats(c: Course) {
  const lessons = allLessons(c);
  const states = lessons.map((l) => c.progress.lessons[l.id]);
  const done = states.filter((s) => s?.step === "done").length;
  const tasksPassed = states.filter((s) => s?.taskReview?.passed).length;
  const results = states.map(quizResult).filter((r): r is { correct: number; total: number } => !!r);
  const quizPct = results.length
    ? Math.round((100 * results.reduce((a, r) => a + r.correct, 0)) / results.reduce((a, r) => a + r.total, 0))
    : null;
  return { total: lessons.length, done, tasksPassed, quizPct, pct: lessons.length ? Math.round((100 * done) / lessons.length) : 0 };
}

/** What the tutor knows about how the learner is doing — fed into every generation call. */
export function masterySummary(c: Course) {
  const weak: string[] = [];
  let q = 0, qc = 0;
  for (const l of allLessons(c)) {
    const s = c.progress.lessons[l.id];
    if (!s) continue;
    const r = quizResult(s);
    if (r && r.correct / r.total < 0.6) weak.push(l.title);
    for (const a of Object.values(s.answers)) { q++; if (a.correct) qc++; }
  }
  const stats = courseStats(c);
  return {
    lessons_completed: stats.done,
    quiz_accuracy_pct: stats.quizPct,
    practice_question_accuracy_pct: q ? Math.round((100 * qc) / q) : null,
    struggling_with: weak.slice(0, 4),
    stage: c.stage,
  };
}

/** Per-lesson performance, used to tune that lesson's task and quiz difficulty. */
export function lessonPerformance(s: LessonState) {
  const answers = Object.values(s.answers);
  return {
    practice_correct: answers.filter((a) => a.correct).length,
    practice_total: answers.length,
    task_attempts: s.taskAttempts,
    task_passed: !!s.taskReview?.passed,
  };
}

export function nextLesson(c: Course, afterId?: string | null): LessonRef | null {
  const lessons = allLessons(c);
  const start = afterId ? lessons.findIndex((l) => l.id === afterId) + 1 : 0;
  return lessons.slice(start).find((l) => !isDone(c, l.id)) ?? lessons.find((l) => !isDone(c, l.id)) ?? null;
}

export type Recommendation =
  | { kind: "continue"; text: string }
  | { kind: "review"; text: string; lessonIds: string[] }
  | { kind: "advance"; text: string; next: Stage }
  | { kind: "finished"; text: string };

/** The "what should I do next" advice shown on the course screen. */
export function recommend(c: Course): Recommendation {
  const stats = courseStats(c);
  if (stats.done < stats.total) {
    const nxt = nextLesson(c, c.current_lesson_id);
    return { kind: "continue", text: nxt ? `Next up: ${nxt.title}` : "Keep going" };
  }
  const weak = allLessons(c).filter((l) => {
    const r = quizResult(c.progress.lessons[l.id]);
    return r && r.correct / r.total < 0.6;
  });
  const idx = STAGES.indexOf(c.stage);
  if (weak.length && idx < STAGES.length - 1) {
    return { kind: "review", text: `Before moving on, revisit: ${weak.map((l) => l.title).join(", ")}`, lessonIds: weak.map((l) => l.id) };
  }
  if (c.is_coding && idx < STAGES.length - 1) {
    const next = STAGES[idx + 1];
    return { kind: "advance", text: `You've finished ${STAGE_LABEL[c.stage]}. Ready for ${STAGE_LABEL[next]}?`, next };
  }
  return { kind: "finished", text: c.is_coding ? "You've completed the whole path — Basic to Pro. Outstanding." : "You've completed this course." };
}

// ---- small shared utilities -------------------------------------------------
export function resetLesson(c: Course, id: string): Progress {
  const lessons = { ...c.progress.lessons };
  delete lessons[id];
  return { ...c.progress, lessons };
}

export const CODING_LANGUAGES = ["Python", "JavaScript", "TypeScript", "Java", "Kotlin", "C++", "C#", "PHP", "Go", "Rust", "SQL", "Dart"];
export const LEVELS = ["Complete beginner", "Some experience", "Comfortable", "Experienced"];
export const RUNNABLE_NOTE: Record<string, string> = {
  javascript: "Runs in the in-app console",
  python: "Runs in the in-app console",
};
export function looksLikeCoding(subject: string): boolean {
  return /\b(code|coding|programming|program|python|javascript|typescript|java|kotlin|swift|c\+\+|c#|php|golang|rust|sql|html|css|react|node|flutter|dart|android|developer|software|algorithm|data structures?)\b/i.test(subject);
}
export function guessLanguage(subject: string): string | null {
  const map: [RegExp, string][] = [
    [/typescript/i, "TypeScript"], [/javascript|\bjs\b|node|react/i, "JavaScript"], [/python/i, "Python"], [/kotlin/i, "Kotlin"],
    [/\bjava\b/i, "Java"], [/c\+\+/i, "C++"], [/c#|csharp/i, "C#"], [/php/i, "PHP"], [/\bgo(lang)?\b/i, "Go"], [/rust/i, "Rust"],
    [/sql/i, "SQL"], [/dart|flutter/i, "Dart"],
  ];
  return map.find(([re]) => re.test(subject))?.[1] ?? null;
}
